# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: H:/ES3B2/LabyrinthFPGA/Nexys4 _Master.xdc

# IP: ip/dist_mem_gen_astro_1/dist_mem_gen_astro.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_astro || ORIG_REF_NAME==dist_mem_gen_astro}]

# IP: ip/dist_mem_gen_galaxy/dist_mem_gen_galaxy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_galaxy || ORIG_REF_NAME==dist_mem_gen_galaxy}]
