# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.cache/wt} [current_project]
set_property parent.project_path {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/blackholeCOE.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/minecraftDirtCOE.COE
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/minecraftOBSCOE.COE
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/SuhaibCOE.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/astro.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/XilinxCOE.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/minecraftCobStone.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/earthCOE.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/windows.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/blackhole2COE.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/blackhole2.coe.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/astropinkCOE.coe
add_files H:/ES3B2/LabyrinthFPGA/etc/COE/SuhaibpinkCOE.coe
read_verilog -library xil_defaultlib {
  {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/new/LED.v}
  {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/new/RGB_LED.v}
  {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/new/accel.v}
  {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/new/drawcon.v}
  {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/new/vga_out.v}
  {H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/new/game_top.v}
}
read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_astro_1/dist_mem_gen_astro.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_astro_1/dist_mem_gen_astro_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_astro_1/dist_mem_gen_astro.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_galaxy/dist_mem_gen_galaxy.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_galaxy/dist_mem_gen_galaxy_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_galaxy/dist_mem_gen_galaxy.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftDirt/dist_mem_gen_minecraftDirt.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftDirt/dist_mem_gen_minecraftDirt_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftDirt/dist_mem_gen_minecraftDirt.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dis_mem_gen_ball2/dis_mem_gen_ball2.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dis_mem_gen_ball2/dis_mem_gen_ball2_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dis_mem_gen_ball2/dis_mem_gen_ball2.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_xilinx/dist_mem_gen_xilinx.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_xilinx/dist_mem_gen_xilinx_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_xilinx/dist_mem_gen_xilinx.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftCobStone/dist_mem_gen_minecraftCobStone.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftCobStone/dist_mem_gen_minecraftCobStone_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftCobStone/dist_mem_gen_minecraftCobStone.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_earth/dist_mem_gen_earth.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_earth/dist_mem_gen_earth_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_earth/dist_mem_gen_earth.xci}}]

read_ip -quiet {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_windows/dist_mem_gen_windows.xci}}
set_property used_in_implementation false [get_files -all {{h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_windows/dist_mem_gen_windows_ooc.xdc}}]
set_property is_locked true [get_files {{H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_windows/dist_mem_gen_windows.xci}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{H:/ES3B2/LabyrinthFPGA/Nexys4 _Master.xdc}}
set_property used_in_implementation false [get_files {{H:/ES3B2/LabyrinthFPGA/Nexys4 _Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top game_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef game_top.dcp

catch { report_utilization -file game_top_utilization_synth.rpt -pb game_top_utilization_synth.pb }
