# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dis_mem_gen_ball2/dis_mem_gen_ball2.xci
# IP: The module: 'dis_mem_gen_ball2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dis_mem_gen_ball2/dis_mem_gen_ball2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dis_mem_gen_ball2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dis_mem_gen_ball2/dis_mem_gen_ball2.xci
# IP: The module: 'dis_mem_gen_ball2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dis_mem_gen_ball2/dis_mem_gen_ball2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dis_mem_gen_ball2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
