# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftDirt/dist_mem_gen_minecraftDirt.xci
# IP: The module: 'dist_mem_gen_minecraftDirt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftDirt/dist_mem_gen_minecraftDirt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_minecraftDirt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: H:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftDirt/dist_mem_gen_minecraftDirt.xci
# IP: The module: 'dist_mem_gen_minecraftDirt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ES3B2/LabyrinthFPGA/Lab4 - VGA Output.srcs/sources_1/ip/dist_mem_gen_minecraftDirt/dist_mem_gen_minecraftDirt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_minecraftDirt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
